'/Script/CoreUObject.Object':
- '/Script/Engine.Actor':
    - '/Script/Engine.Brush'
        - '/Script/Engine.Volume'
            - '/Script/ShooterGame.BiomeZoneVolume'
            - '/Script/Engine.PostProcessVolume'
                - '/Script/Engine.SpherePostProcessVolume'
    - '/Script/Engine.Emitter'
        - '/Script/ShooterGame.PrimalEmitterSpawnable'
        - '/Script/ShooterGame.PrimalBuff'
    - '/Script/Engine.Info': # Done
        - '/Script/ShooterGame.DayCycleManager'
        - '/Script/Engine.GameMode':
            - '/Script/ShooterGame.LocalSpawnGameMode'
            - '/Script/ShooterGame.ShooterGame_Menu'
            - '/Script/ShooterGame.ShooterGameMode':
                - '/Script/ShooterGame.CustomGameMode'
        - '/Script/Engine.GameState':
            - '/Script/ShooterGame.ShooterGameState':
                - '/Script/ShooterGame.BattleGameState'
                - '/Script/ShooterGame.CustomGameState'
        - '/Script/ShooterGame.MatineeActorManager'
        - '/Script/ShooterGame.NPCZoneManager'
        - '/Script/Engine.PlayerState':
            - '/Script/ShooterGame.ShooterPlayerState'
        - '/Script/ShooterGame.PrimalStructurePlacer'
        - '/Script/Engine.SkyLight'
    - '/Script/Engine.ReflectionCapture'
        - '/Script/Engine.BoxReflectionCapture'
        - '/Script/Engine.PlaneReflectionCapture'
        - '/Script/Engine.SphereReflectionCapture'
    - '/Script/ShooterGame.DroppedItem': # Done
        - '/Script/ShooterGame.DroppedItemEgg'
        - '/Script/ShooterGame.DroppedItemLowQuality':
            - '/Script/ShooterGame.DroppedItemTorch'
    - '/Script/ShooterGame.PrimalTargetableActor': # Done
        - '/Script/ShooterGame.PrimalStructure':
            - '/Script/ShooterGame.PrimalStructureBearTrap'
            - '/Script/ShooterGame.PrimalStructureDoor':
                - '/Script/ShooterGame.PrimalStructureSkeletalDoor'
            - '/Script/ShooterGame.PrimalStructureElevatorPlatform'
            - '/Script/ShooterGame.PrimalStructureExplosive':
                - '/Script/ShooterGame.PrimalStructureExplosiveTransGPS'
                - '/Script/ShooterGame.PrimalStructureTripwire'
            - '/Script/ShooterGame.PrimalStructureItemContainer':
                - '/Script/ShooterGame.PrimalStructureElevatorTrack'
                - '/Script/ShooterGame.PrimalStructureItemContainer_CropPlot':
                    - '/Script/ShooterGame.PrimalStructureItemContainer_CropPlot_VisualItems'
                - '/Script/ShooterGame.PrimalStructureItemContainer_SupplyCrate':
                    - '/Script/ShooterGame.PrimalStructureItemContainer_HordeCrate'
                - '/Script/ShooterGame.PrimalStructureItemContainer_VisualItems'
                - '/Script/ShooterGame.PrimalStructureKeypad'
                - '/Script/ShooterGame.PrimalStructureMovingContainer'
                - '/Script/ShooterGame.PrimalStructureSeating':
                    - '/Script/ShooterGame.PrimalStructureBed'
                    - '/Script/ShooterGame.PrimalStructureSeatingMusic'
                    - '/Script/ShooterGame.PrimalStructureTurretBallista'
                - '/Script/ShooterGame.PrimalStructureTurret':
                    - '/Script/ShooterGame.PrimalStructureTurretPlant'
                - '/Script/ShooterGame.PrimalStructureUnderwaterBase'
            - '/Script/ShooterGame.PrimalStructureLadder':
                - '/Script/ShooterGame.PrimalStructurePortableLadder'
            - '/Script/ShooterGame.PrimalStructureSeaMine'
            - '/Script/ShooterGame.PrimalStructureSign'
            - '/Script/ShooterGame.PrimalStructureWaterPipe'
    - '/Script/ShooterGame.ShooterProjectile': # Done
        - '/Script/ShooterGame.PrimalProjectileArrow':
            - '/Script/ShooterGame.PrimalProjectileBoomerang'
            - '/Script/ShooterGame.PrimalProjectileNetGun'
        - '/Script/ShooterGame.PrimalProjectileDilo'
        - '/Script/ShooterGame.PrimalProjectileFlare'
        - '/Script/ShooterGame.PrimalProjectileGrapplingHook'
        - '/Script/ShooterGame.PrimalProjectileSpiderAcid'
        - '/Script/ShooterGame.ShooterProjectile_Swarm'
    - '/Script/ShooterGame.ShooterWeapon': # Done
        - '/Script/ShooterGame.ShooterWeapon_ChainSaw'
        - '/Script/ShooterGame.ShooterWeapon_FlameThrower'
        - '/Script/ShooterGame.ShooterWeapon_Instant':
            - '/Script/ShooterGame.ShooterWeapon_InstantPenetrating'
        - '/Script/ShooterGame.ShooterWeapon_Melee':
            - '/Script/ShooterGame.PrimalWeaponElectronicBinoculars'
            - '/Script/ShooterGame.PrimalWeaponGPS'
            - '/Script/ShooterGame.ShooterWeapon_Climb'
            - '/Script/ShooterGame.ShooterWeapon_Whip'
        - '/Script/ShooterGame.ShooterWeapon_Placer':
            - '/Script/ShooterGame.ShooterWeapon_PlacerTransGPS'
        - '/Script/ShooterGame.ShooterWeapon_Projectile':
            - '/Script/ShooterGame.PrimalWeaponBow':
                - '/Script/ShooterGame.PrimalWeaponBoomerang'
            - '/Script/ShooterGame.PrimalWeaponGrapplingHook'
            - '/Script/ShooterGame.PrimalWeaponGrenade'
    - '/Script/Engine.LevelScriptActor'
    - '/Script/Engine.MatineeActor'
    - '/Script/Engine.Note'
    - '/Script/ShooterGame.DestructibleActor'
        - '/Script/ShooterGame.DestroyedMeshActor'
        - '/Script/ShooterGame.FadingDestructibleActor'
    - '/Script/Engine.Light'
        - '/Script/Engine.DirectionalLight'
        - '/Script/Engine.PointLight'
        - '/Script/Engine.SpotLight'
    - '/Script/Engine.Controller'
        - '/Script/Engine.AIController'
            - '/Script/ShooterGame.PrimalDinoAIController'
    - '/Script/Engine.Pawn'
        - '/Script/Engine.Character'
            - '/Script/ShooterGame.PrimalCharacter'
                - '/Script/ShooterGame.ShooterCharacter'
                - '/Script/ShooterGame.PrimalDinoCharacter'
                    - '/Script/ShooterGame.PrimalRaft'
                    - '/Script/ShooterGame.PrimalWheeledVehicleCharacter'
        - '/Script/Engine.WheeledVehicle'
    - '/Script/ShooterGame.GroundClutterLayerActor'
    - '/Script/Engine.StaticMeshActor'
    - '/Script/Engine.SplineActor'
    - '/Script/Engine.HierarchicalInstancedStaticMeshActor'
    - '/Script/Engine.TargetPoint'
    - '/Script/ShooterGame.BiomeZoneSettings'
    - '/Script/ShooterGame.TerrainActor'
    - '/Script/ShooterGame.TargetArea'
    - '/Script/ShooterGame.HordeCrateManager'
- '/Script/Engine.ActorComponent':
    - '/Script/Engine.SceneComponent'
        - '/Script/Engine.PrimitiveComponent'
            - '/Script/Engine.MeshComponent'
                - '/Script/Engine.StaticMeshComponent'
                    - '/Script/Engine.InstancedStaticMeshComponent'
                        - '/Script/Engine.HierarchicalInstancedStaticMeshComponent'
    - '/Script/ShooterGame.PrimalInventoryComponent':
        - '/Script/ShooterGame.PrimalInventoryComponent_Static'
    - '/Script/ShooterGame.PrimalCharacterStatusComponent'
        - '/Script/ShooterGame.PrimalDinoStatusComponent'
    - '/Script/ShooterGame.PrimalHarvestingComponent'
- '/Script/ShooterGame.PrimalItem':
    - '/Script/ShooterGame.PrimalItem_Dye'
    - '/Script/ShooterGame.PrimalItem_Radio'
- '/Script/ShooterGame.PrimalStructureSettings'
- '/Script/Engine.BlueprintFunctionLibrary'
- '/Script/Engine.AnimInstance'
    - '/Script/Engine.VehicleAnimInstance'
- '/Script/Engine.AnimNotify'
- '/Script/Engine.AnimNotifyState'
- '/Script/Engine.VehicleWheel'
- '/Script/Engine.CameraShake'
- '/Script/ShooterGame.NPCSpawnEntriesContainer'
- '/Script/ShooterGame.PrimalBuffPersistentData'
- '/Script/ShooterGame.PrimalDinoSettings'
- '/Script/ShooterGame.PrimalDinoEntry'
- '/Script/ShooterGame.PrimalPlayerData'
- '/Script/ShooterGame.FogOfWar'
- '/Script/ShooterGame.TerrainGenerator'
- '/Script/UMG.Visual'
    - '/Script/UMG.Widget'
        - '/Script/UMG.UserWidget'
            - '/Script/ShooterGame.DataListEntryWidget'
            - '/Script/ShooterGame.ToolTipWidget'
                - '/Script/ShooterGame.PrimalStructureToolTipWidget'
                - '/Script/ShooterGame.PrimalItemInventoryToolTipWidget'
                - '/Script/ShooterGame.PrimalItemToolTipWidget'
                - '/Script/ShooterGame.TargetingInfoToolTipWidget'
            - '/Script/ShooterGame.ContextMenu'
                - '/Script/ShooterGame.ContextMenu_InventorySort'
                - '/Script/ShooterGame.ContextMenu_PrimalItem'
            - '/Script/ShooterGame.ContextMenuItem'
                - '/Script/ShooterGame.ContextMenuItem_Sort'
                - '/Script/ShooterGame.ContextMenuItem_Spinner'
            - '/Script/ShooterGame.UI_Compass'
            - '/Script/ShooterGame.PrimalUI'
                - '/Script/ShooterGame.InventoryPanelWidget'
                - '/Script/ShooterGame.PrimalSubMenuUI'
                    - '/Script/ShooterGame.UI_DinoOrderGroups'
                    - '/Script/ShooterGame.UI_TribeManager'
                    - '/Script/ShooterGame.UI_SurvivorProfile'
                    - '/Script/ShooterGame.UI_Inventory'
                    - '/Script/ShooterGame.UI_OptionsMenu'
                    - '/Script/ShooterGame.UI_EngramsMenu'
                - '/Script/ShooterGame.UI_AdminMangment'
                - '/Script/ShooterGame.UI_AllPlayersList'
                - '/Script/ShooterGame.UI_ChangeTransponderFreqencyEntry'
                - '/Script/ShooterGame.UI_ChatBox'
                - '/Script/ShooterGame.UI_ChatMessage'
                - '/Script/ShooterGame.UI_Cooking'
                - '/Script/ShooterGame.UI_DepthOfFieldMenu'
                - '/Script/ShooterGame.UI_DyeItem'
                - '/Script/ShooterGame.UI_GenericConfirmationDialog'
                - '/Script/ShooterGame.UI_Hairstyle'
                - '/Script/ShooterGame.UI_HelpPage'
                - '/Script/ShooterGame.UI_HostSession'
                - '/Script/ShooterGame.UI_Hub'
                - '/Script/ShooterGame.UI_HudOverlay'
                - '/Script/ShooterGame.UI_ListCharacterData'
                - '/Script/ShooterGame.UI_ListSessions'
                    - '/Script/ShooterGame.UI_ClusterServersListSessions'
                - '/Script/ShooterGame.UI_MainMenu'
                - '/Script/ShooterGame.UI_MapMarkersEntry'
                - '/Script/ShooterGame.UI_MultiUse'
                - '/Script/ShooterGame.UI_Notification'
                - '/Script/ShooterGame.UI_PaintingsList'
                - '/Script/ShooterGame.UI_PauseMenu'
                - '/Script/ShooterGame.UI_PinEntry'
                - '/Script/ShooterGame.UI_ProceduralSettings'
                - '/Script/ShooterGame.UI_SavePainting'
                - '/Script/ShooterGame.UI_ServerBroadcastMessage'
                - '/Script/ShooterGame.UI_Spawn'
                - '/Script/ShooterGame.UI_SpawnPoint'
                - '/Script/ShooterGame.UI_SteamInventoryStatusPopup'
                - '/Script/ShooterGame.UI_Subtitles'
                - '/Script/ShooterGame.UI_TextEntry'
                - '/Script/ShooterGame.UI_TribeWarEntry'
                - '/Script/ShooterGame.UI_Tutorial'
                - '/Script/ShooterGame.DataListEntryButton_DyeResources'
                - '/Script/ShooterGame.DataListEntryEngramList'
                - '/Script/ShooterGame.BaseSelectableButtonWidget'
                    - '/Script/ShooterGame.DataListEntryButton_HostSession'
                    - '/Script/ShooterGame.DataListEntryButton_ListSession'
                    - '/Script/ShooterGame.DataListEntryButton_MainMenu'
- '/Script/ShooterGame.PrimalAIState'
    - '/Script/ShooterGame.PrimalAIStateBPBase'
    - '/Script/ShooterGame.PrimalAIStateDinoMeleeState'
        - '/Script/ShooterGame.PrimalAIStateDinoFlyerGrab'
        - '/Script/ShooterGame.PrimalAIStateDinoGrabAndReleaseState'
    - '/Script/ShooterGame.PrimalAIStateDinoRangedState'
        - '/Script/ShooterGame.PrimalAIStateDinoSpiderRangedWebState'
        - '/Script/ShooterGame.PrimalAIStateDinoSpineyLizardTailRangeState'
    - '/Script/ShooterGame.PrimalAIStateDinoSpiderMinions'
    - '/Script/ShooterGame.PrimalAIStateDinoSpiderRangedAcidState'
- '/Script/AIModule.BTNode'
    - '/Script/AIModule.BTAuxiliaryNode'
        - '/Script/AIModule.BTDecorator'
            - '/Script/AIModule.BTDecorator_BlueprintBase'
                - '/Script/AIModule.BTDecorator_BlueprintBase_New'
                - '/Script/AIModule.BTDecorator_BlueprintBase_New2'
                - '/Script/AIModule.BTDecorator_CheckUseSpline'
        - '/Script/AIModule.BTService'
            - '/Script/AIModule.BTService_BlueprintBase'
                - '/Script/AIModule.BTService_BlueprintBase_New'
        - '/Script/AIModule.BTTask'
            - '/Script/AIModule.BTTask_BlueprintBase'
                - '/Script/AIModule.BTTask_BlueprintBase_New'

# Unknown, need placing
- '/Engine/Transient.REINST_ElementWall_Horde_C_8303'
- '/Script/CoreUObject.Interface'
- '/Script/ShooterGame.CharacterViewPanelWidget'
- '/Script/ShooterGame.DinoAncestryEntryWidget'
- '/Script/ShooterGame.DinoListButtonWidget'
- '/Script/ShooterGame.DinoListItemTooltip'
- '/Script/ShooterGame.DyeRegionButtonWidget'
- '/Script/ShooterGame.GamepadButtonLegendWidget'
- '/Script/ShooterGame.HUDCustomStatusWidget'
- '/Script/ShooterGame.HUDElementBarWidget'
- '/Script/ShooterGame.HUDStatusBarsWidget'
- '/Script/ShooterGame.InventoryArkCreaturesPanel'
- '/Script/ShooterGame.InventoryDinoAncestryPanel'
- '/Script/ShooterGame.InventoryStatsPanel'
- '/Script/ShooterGame.PlayerHUDUI'
- '/Script/ShooterGame.PrimalClimbingSettings'
- '/Script/ShooterGame.PrimalColorSet'
- '/Script/ShooterGame.PrimalDinoToolTipWidget'
- '/Script/ShooterGame.PrimalEmitterSpawnable'
- '/Script/ShooterGame.PrimalEngramEntry'
- '/Script/ShooterGame.PrimalGameData'
- '/Script/ShooterGame.PrimalGlobals'
- '/Script/ShooterGame.PrimalSupplyCrateItemSet'
- '/Script/ShooterGame.PrimalSupplyCrateItemSets'
- '/Script/ShooterGame.RadialSelectorHUD_Inventory'
- '/Script/ShooterGame.RadialSelectorHUD_MultiUse'
- '/Script/ShooterGame.RadialSelectorHUD_PlayerAction'
- '/Script/ShooterGame.SaveGameActorTickable'
- '/Script/ShooterGame.ShooterDamageType'
- '/Script/ShooterGame.ShooterHUD'
- '/Script/ShooterGame.ShooterImpactEffect'
- '/Script/ShooterGame.ShooterPlayerCameraManager'
- '/Script/ShooterGame.ShooterPlayerController'
- '/Script/ShooterGame.StatsPanelWidget_Character'
- '/Script/ShooterGame.StatsPanelWidget_Obelisk'
- '/Script/ShooterGame.StatsPanelWidget_Structure'
- '/Script/ShooterGame.StatWidget'
- '/Script/ShooterGame.StructureStatWidget'
- '/Script/ShooterGame.SupplyCrateSpawningSettings'
- '/Script/ShooterGame.TooltipSmartLayoutWidget'
- '/Script/ShooterGame.TribeManagerListButton'
- '/Script/ShooterGame.TribeMemberButtonWidget'
- '/Script/ShooterGame.TribeWarButtonWidget'
